name: 'Copa Action'
description: 'Patch Vulnerable Images'
inputs:
  image-reports:
    description: 'List of trivy json reports from images to patch'
    required: true
  buildkitd-address:
    description: 'Address of running Buildkitd container'
    required: true
outputs:
  patched-images:
    description: 'List of patched images'
runs:
  steps: 
    - name: docker build action
      shell: bash
      run: |
        docker build -t copa-action .
    - name: docker run action
      shell: bash
      run : |
        docker run --net=host copa-action ${{ github.events.inputs.image-reports }} ${{ github.events.inputs.buildkitd-address }} 
