name: 'Copa'
description: 'Patch Vulnerable Images'
inputs:
  imageReports:
    description: 'List of trivy json reports from images to patch'
    required: true
outputs:
  patchedImages:
    description: 'List of patched images'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.imageReports }}
