name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  images:  # id of input
    description: 'List of images to patch'
    required: true
    default: 'ghcr.io/azure/eraser:v1.1.0-beta.0'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
