name: 'Copa Action'
description: 'Patch Vulnerable Images'
inputs:
  image:
    description: 'The image reference to patch'
    required: true
  image-report:
    description: 'The trivy json report of the image to patch'
    required: true
  patched-tag:
    description: 'The patched image tag to append to the original tag'
    required: true
  buildkit-version:
    description: "Buildkit version to use with Copa"
outputs:
  patched-image:
    description: 'Image reference of patched image'
    value: ${{ steps.copa-action.outputs.patched-image }}
runs:
  using: "composite"
  steps: 
    - name: docker build copa-action
      shell: bash
      run: |
        docker build -t copa-action .
    - name: docker run buildkitd
      shell: bash
      run: |
        docker run --net=host --detach --rm --privileged -p 127.0.0.1:8888:8888 --name buildkitd --entrypoint buildkitd moby/buildkit:${{ inputs.buildkit-version }} --addr tcp://0.0.0.0:8888
    - name: docker run copa-action
      id: copa-action
      shell: bash
      run : |
        docker run --net=host --mount=type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock -e GITHUB_OUTPUT=${{ github.workspace }} copa-action ${{ inputs.image }} ${{ inputs.image-report }} ${{ inputs.patched-tag }} tcp://0.0.0.0:8888
