name: 'Copa Action'
description: 'Patch Vulnerable Images'
inputs:
  image-reports:
    description: 'List of trivy json reports from images to patch'
    required: true
  buildkitd-address:
    description: 'Address of running Buildkitd container'
    required: true
outputs:
  patched-images:
    description: 'List of patched images'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.image-reports }}
    - ${{ inputs.buildkitd-address }}
