name: 'Copa Action'
description: 'Patch Vulnerable Images'
inputs:
  image-reports:
    description: 'List of trivy json reports from images to patch'
    required: true
  buildkitd-address:
    description: 'Address of running Buildkitd container'
    required: true
outputs:
  patched-images:
    description: 'List of patched images'
runs:
  using: "composite"
  steps: 
    - name: docker build action
      shell: bash
      run: |
        docker build -t copa-action .
    - name: docker run action
      shell: bash
      run : |
        docker run --net=host --mount=type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock copa-action ${{ inputs.image-reports }} ${{ inputs.buildkitd-address }} 
