name: "build"
on: [push, pull_request]
env:
  TRIVY_VERSION: 0.44.0
  COPA_VERSION: 0.3.0
permissions: read-all
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Setup BATS
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.7.0

      - name: Check out code
        uses: actions/checkout@v3.5.3

      - name: Install Trivy
        run: |
            curl -fsSL -o trivy.tar.gz https://github.com/aquasecurity/trivy/releases/download/v${{ env.TRIVY_VERSION }}/trivy_${{ env.TRIVY_VERSION }}_Linux-64bit.tar.gz
            tar -zxvf trivy.tar.gz
            cp trivy /usr/local/bin/

      - name: Set up Docker
        uses: docker/setup-buildx-action@ecf95283f03858871ff00b787d79c419715afc34

      - name: Pull docker.io/library/nginx:1.21.6
        run: docker pull docker.io/library/nginx:1.21.6

      - name: Install Copa
        run: |
            curl --retry 5 -fsSL -o copa.tar.gz https://github.com/project-copacetic/copacetic/releases/download/v${{ env.COPA_VERSION }}/copa_${{ env.COPA_VERSION }}_linux_amd64.tar.gz
            tar -zxvf copa.tar.gz 
            cp copa /usr/local/bin/

      - name: Bats Test
        run: |
          docker build --build-arg copa_version=${{ env.COPA_VERSION }} -t copa-action .
          chmod +x ${{ github.workspace }}/entrypoint.sh
          cd ${{ github.workspace }}/test
          bats --print-output-on-failure ./test.bats
