name: build and push copa action image
on: [push]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
          labels: org.opencontainers.image.source=${{ github.repository }}@${{ github.sha }}
        env:
          DOCKER_AUTH_CONFIG: '{"auths":{"ghcr.io":{"username":"$GITHUB_REPOSITORY","password":"${{ secrets.GHCR_TOKEN }}","email":"ashnamehrotra@gmail.com"}}}'
