name: "build"
on: [push, pull_request]
env:
  COPA_VERSION: 0.3.0
permissions: write-all
jobs:
  build:
    name: build
    runs-on: ubuntu-20.04
    steps:
      - name: Setup BATS
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.7.0

      - name: Check out code
        uses: actions/checkout@v1

      - name: Set up Trivy
        uses: aquasecurity/trivy-action@master

      - name: Set up Docker
        uses: docker/setup-buildx-action@ecf95283f03858871ff00b787d79c419715afc34

      - name: Install Copa
        run: |
            curl --retry 5 -fsSL -o copa.tar.gz https://github.com/project-copacetic/copacetic/releases/download/v${{ env.COPA_VERSION }}/copa_${{ env.COPA_VERSION }}_linux_amd64.tar.gz
            tar -zxvf copa.tar.gz 
            cp copa /usr/local/bin/

      - name: Pull docker.io/library/nginx:1.21.6 for test
        run: docker pull docker.io/library/nginx:1.21.6

      - name: Bats Test
        run: |
          chmod +x ${{ github.workspace }}/entrypoint.sh
          cd ${{ github.workspace }}/test
          ./test.bats
