on: [push]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: copa action
          id: copa
          uses: ashnamehrotra/test-action@v1.5.3
          with:
            image-reports: 'nginx.1.21.6.json'

        - name: View Output
          run: echo "${{ steps.copa.outputs.patched-images }}"
