on: [push]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Set up Docker Buildx to start Buildkit
          uses: docker/setup-buildx-action@v2

        - name: Create and run buildkitd container
          run: |
            docker network create mynetwork
            docker run --detach --rm --privileged -p 127.0.0.1:8888:8888 --network=mynetwork --name buildkitd --entrypoint buildkitd moby/buildkit:v0.11.4 --addr tcp://0.0.0.0:8888
            BUILDKITD_SOCKET=/var/run/docker.sock
            echo "BUILDKITD_SOCKET=$BUILDKITD_SOCKET" >> $GITHUB_ENV

        - name: copa action
          uses: ashnamehrotra/test-action@v1.1.9
          with:
            image-reports: 'nginx.1.21.6.json'
            buildkitd-address: unix://${{ env.BUILDKITD_SOCKET }}
          env:
            DOCKER_HOST: unix://${{ env.BUILDKITD_SOCKET }}
            DOCKER_BUILDKIT: 1
