on: [push]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: copa action
          uses: ashnamehrotra/test-action@v1.4.2
          with:
            image-reports: 'nginx.1.21.6.json, nginx.1.21.6.json,'
