on: [push]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
          with: 
            builkitd-flags: '--debug --addr=tcp://0.0.0.0:8888'

        - name: Create and run buildkitd container
          run: |
            docker run --detach --rm --privileged -p 127.0.0.1:8888:8888 --name buildkitd --entrypoint buildkitd moby/buildkit:v0.11.4 --addr tcp://0.0.0.0:8888

        - name: copa action
          uses: ashnamehrotra/test-action@v1.1.4
          with:
            image-reports: 'nginx.1.21.6.json'
            buildkitd-address: 'tcp://127.0.0.1:8888'
