on: [push]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Set up Docker Buildx to start Buildkit
          uses: docker/setup-buildx-action@v2

        - name: copa action
          uses: ashnamehrotra/test-action@v1.3.1
          with:
            image-reports: 'nginx.1.21.6.json'
            buildkitd-address: unix://${{ env.BUILDKITD_SOCKET }}
          env:
            DOCKER_HOST: unix://${{ env.BUILDKITD_SOCKET }}
            DOCKER_BUILDKIT: 1
