on: [push]

jobs:
    test:
        runs-on: ubuntu-latest

        services:
          buildkitd:
            image: moby/buildkit:v0.11.4
            ports:
              - 8888:8888
            options: --privileged --name buildkitd --entrypoint buildkitd --addr tcp://0.0.0.0:8888

        steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Set up Docker Buildx to start Buildkit
          uses: docker/setup-buildx-action@v2

        - name: Create and run buildkitd container
          run: |
            docker network create mynetwork
            docker run --detach --rm --privileged -p 127.0.0.1:8888:8888 --network=mynetwork --name buildkitd --entrypoint buildkitd moby/buildkit:v0.11.4 --addr tcp://0.0.0.0:8888

        - name: copa action
          uses: ashnamehrotra/test-action@v1.1.7
          with:
            image-reports: 'nginx.1.21.6.json'
            buildkitd-address: 'tcp://buildkitd:8888'
          env:
            DOCKER_BUILDKIT: 1
