on: [push]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - name: Set up Docker Buildx to start Buildkit
          uses: docker/setup-buildx-action@v2
        - name: copa action
          uses: ashnamehrotra/test-action@v1.1.6
          with:
            image-reports: 'nginx.1.21.6.json'
            buildkitd-address: 'tcp://0.0.0.0:8888'
