on: [push]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: copa action
          id: copa
          uses: ashnamehrotra/test-action@v1.4.9
          with:
            image-reports: 'nginx.1.21.6.json'

        - name: View Output
          run: |
            echo "copa output: ${{ steps.copa.outputs.patched-images }}"
