on: [push]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - name: copa action
          uses: ashnamehrotra/test-action@v1
          with:
            image-reports: nginx.1.21.6.json
            buildkitd-address: tcp://0.0.0.0:8888
