name: Release

on:
  workflow_dispatch:
    inputs:
      # without the  v
      copa-version:
        description: 'Copa Version'
        required: true
            
jobs:
    release:
        runs-on: ubuntu-latest
        steps:

        - name: Checkout Repository
          uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        
        - name: Set up Docker
          uses: docker/setup-buildx-action@4c0219f9ac95b02789c1075625400b2acbff50b1 # v2.9.1

        - name: Login to ghcr.io
          uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # v2.2.0
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Build and push copa-action image with new version
          run: |
            docker buildx build --build-arg copa_version=${{ github.event.inputs.copa-version }} -t ghcr.io/ashnamehrotra/copa-action:v"$tag" --push .
